### PR TITLE
chore: update dependency, bump version

### PR DESCRIPTION
**Pull request by yuanbohan**
GreptimeAI won't take langchain, tiktoken as a necessary dependency.

- remove langchain dependency
- add openai optional dependency, and move tiktoken into it. Like if you want to calculate OpenAI streaming token and cost, you can: `pip install 'langchain[openai]'`

and I will update greptimeai-cookbook based on this update

### CODE REVIEW

**Review by sunng87 — APPROVED** [review]

**Comment by sunng87** [comment]
Sounds good for us to assume langchain as a provided dependency. But we might need to update docs to reflect the change.

**Comment by yuanbohan** [comment]
> Sounds good for us to assume langchain as a provided dependency. But we might need to update docs to reflect the change.

👍  
What about only show basic setup for GreptimeAI, and leave code samples for specific framework in `examples` or greptimeai-cookbook.

**Comment by yuanbohan** [comment]
> Sounds good for us to assume langchain as a provided dependency. But we might need to update docs to reflect the change.

Actually, GreptimeAI acts as a dependency of the Framework or Service

**Comment by yuanbohan** [comment]
and I will update greptimeai-cookbook based on this update

**Comment by sunng87** [comment]
Yes, we can change installation step to `pip install langchain greptimeai`

**Pull request merged**
